//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealPost
    {
        public int id { get; set; }
        public string userimage { get; set; }
        public string postheader { get; set; }
        public string postbody { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public Nullable<int> comments { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> share { get; set; }
        public string postid { get; set; }
        public string usermobile { get; set; }
        public string userdate { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public string image4 { get; set; }
        public string image5 { get; set; }
    }
}
