//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REALESTATEEntities : DbContext
    {
        public REALESTATEEntities()
            : base("name=REALESTATEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RealAllError> RealAllErrors { get; set; }
        public DbSet<RealComment> RealComments { get; set; }
        public DbSet<RealPost> RealPosts { get; set; }
        public DbSet<RealPostsImage> RealPostsImages { get; set; }
        public DbSet<RealREGUSER> RealREGUSERs { get; set; }
        public DbSet<RealSavedpost> RealSavedposts { get; set; }
        public DbSet<Realrequest> Realrequests { get; set; }
    }
}
