//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealREGUSER
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string job_title { get; set; }
        public string imageurl { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> usertype { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
