//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realrequest
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string datecomment { get; set; }
        public string userimage { get; set; }
        public string mobileno { get; set; }
    }
}
